# Generated by Django 6.1.2 on 2026-10-08 16:27

import sorry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SorryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=sorry.models.generate_page_slug, editable=False, max_length=32, unique=True)),
                ('her_name', models.CharField(max_length=100)),
                ('your_name', models.CharField(max_length=100)),
                ('theme', models.CharField(default='romantic', max_length=20)),
                ('sorry_message', models.TextField()),
                ('letter_title', models.CharField(blank=True, max_length=160)),
                ('letter_body', models.TextField(blank=True)),
                ('signature', models.CharField(blank=True, max_length=160)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_caption', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
