# Generated by Django 6.1.2 on 2026-10-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sorry_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sorry.sorrypage')),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
    ]
