# Generated by Django 6.1.2 on 2026-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorry', '0002_sorryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorrypage',
            name='memory_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='sorrypage',
            name='sorry_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
