# Generated by Django 6.1.2 on 2026-10-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorry', '0003_sorrypage_memory_video_sorrypage_sorry_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(upload_to='people_messages/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sorry_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_messages', to='sorry.sorrypage')),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
    ]
